### ISSUE TITLE
helpers with arguments?

### ISSUE THREAD

**Issue by akhoury** [benchpressjs/benchpressjs#6]
can I create helpers and pass them arguments? 
do you support something like:

```
templates.registerHelper('x', function(data, iterator, blocks, args /* maybe? */ ) {
    var fn = function(){}, result;
    try {
      fn = Function.apply(this,["window", "return " + args[0] + " ;"]);
    } catch (e) {
      console.warn("{{x " + args[0] + "}} has invalid javascript", e);
    }

    try {
      result = fn.call(data, window);
    } catch (e) {
      console.warn("{{x " + args[0] + "}} hit a runtime error", e);
    }
    return result;
});

```

**Comment by psychobunny** [comment]
I missed this issue. Currently we do have this support

`{function.myMethod, arg1, arg2, arg3}`

Where arg1, arg2, and arg3 are actually keys in the current array/object scope. I want to change this to the following (to match your expectations as well @akhoury, which I agree with)

`{function.myMethod, {someKey}, "custom variable", {anotherObject.key}}`

@julianlam this would affect you as you've already built something with this system afaik.

RFC, not sure to keep current system or expand on it.

**Comment by psychobunny** [comment]
Alternate is to keep expected functionality, and anything with single/double quotes gets interpreted as a string as so:

`{function.myMethod, someKey, "my custom variable"}`

ping @barisusakli for pro advice

**Comment by julianlam** [comment]
Is there a need to specifically pass values instead of scope? I'm game for any changes :y:

**Comment by psychobunny** [comment]
random example

1. core helper toggles favourite button
2. theme sends in off and on state as string

**Comment by akhoury** [comment]
yea, another example 
`{function.format "string"}`

**Comment by psychobunny** [comment]
pinging @cnvo as well :)

for me, I think I like this the most:

`{function.myMethod, someKey, "my custom variable"}`

**Comment by akhoury** [comment]
`{function.x 'any JS expression'}` FTW

**Comment by psychobunny** [comment]
sounds like I'd have to use  `eval` though. Any other framework uses this? I'll have a peek at how they accomplish it

**Comment by akhoury** [comment]
oh no no, you just need to provide a way to register a helper and be able to pass it any arguments, you do NOT have to use `eval`. 

Then each helper can do whatever it wants, mine would use something similar to eval, check the OP

```
templates.registerHelper('x', function(data, iterator, blocks, myCustomArgument) {
  ...
});
```

**Comment by cnvo** [comment]
``{function.x 'any JS expression'}`` - LOL.

``{function.myMethod, someKey, "my custom variable"}`` - Looks like a really viable solution to further customization and I'm all for it. Could you explain to me how this would work in detail - perhaps like an example because I would really love to use this if its as simple as it sounds.

`````
templates.registerHelper('x', function(data, iterator, blocks, myCustomArgument) {
  ...
});
````
Never mind on the explanation, this makes more sense to me.

**Comment by pitaj** [comment]
Just figured I'd comment that [my fork](https://github.com/pitaj/templates.js) has the capacity to pass in strings and context arguments.

**Comment by patiernom** [comment]
Is not the truth.... for me you have never tried this case, it does not work!!!
Because if you try to pass parameters to a helper that is what happens:
{function.helpertester, posts, "bla bla"}
{function.helpertester, {data: posts}, "bla bla"}
{function.helpertester, {posts}, "bla bla"}
Console.log result --->
{ '0': undefined, '1': undefined }
{ '0': undefined, '1': undefined }
{ '0': undefined, '1': undefined }

It works only if the parameter is at the first level of the context data.

**Comment by pitaj** [comment]
In Benchpress you can use string arguments like this:
```text
{function.caps, "lower case"}
```
->
```text
LOWER CASE
```
