### ISSUE TITLE
Object.keys called on empty string

### ISSUE THREAD

**Issue by BenLubar** [benchpressjs/benchpressjs#73]
https://github.com/benchpressjs/benchpressjs/blob/a057db6faa9b468058987e4c623961d839e23ea4/lib/compiler/runtime.js#L20

I have a user on Firefox 22 (yes, I know) who cannot access my forum because calling `Object.keys("")` throws `TypeError: Value not an object.`

`get` is frequently used as input to `iter`: https://github.com/benchpressjs/benchpressjs/blob/a057db6faa9b468058987e4c623961d839e23ea4/lib/compiler/runtime.js#L9

It seems like returning an empty array would be better than returning an empty string for a function that takes an array and tries to make it non-null.

**Comment by pitaj** [comment]
`get` has a two purposes:

- Output an empty string if `null` or `undefined`
- Convert an empty array to a falsy value so it's treated as falsy in conditionals etc

The reason this bug exists on the older Firefox browser is because the ES5 standard specified that `Object.keys` should throw if the argument is not an object. Under ES2015, this behavior was instead changed to coerce the argument to an object first.

So I'll just add a fix for this in `each`, adding an `Object(obj)` coercion.

**Comment by pitaj** [comment]
Fixed in benchpressjs@1.0.4
