### ISSUE TITLE
Strange problem when going from old syntax to new syntax

### ISSUE THREAD

**Issue by alfazaz** [benchpressjs/benchpressjs#99]
Hello !

This issue is created after this nodebb community topic :
https://community.nodebb.org/topic/15235

I tried to convert all `<!-- IF toto --> xxxxxx <!-- ENDIF toto -->` in my templates and I detected a strange thing you can reproduce like the following.

* Use persona theme.
* Replace `templates/partials/menu.tpl` with `menu.tpl_working` which is in [this attached zip file](https://github.com/benchpressjs/benchpressjs/files/5761999/menus.zip), build and run nodebb : menu elements are visible at the top.
* Replace `templates/partials/menu.tpl` with `menu.tpl_notworking` which is in [this attached zip file](https://github.com/benchpressjs/benchpressjs/files/5761999/menus.zip), build and run nodebb : menu elements are not present.

The only difference between these two templates is the use of
```
<!-- IF function.displayMenuItem, @index -->
xxxxx
<!-- ENDIF function.displayMenuItem -->

```
in the working version. In the other one, which uses the following new syntax (?), it doesn't work : 
```
{{{ if function.displayMenuItem, @index }}}
xxxxx
{{{end}}}

```
Or I made a mistake somewhere ?

**Comment by pitaj** [comment]
This is due to [some transformations done for backwards-compatibility](https://github.com/benchpressjs/benchpressjs/blob/master/docs/helpers.md#note-about-alternate-syntax). Specifically, this:

> In a conditional test, helpers are automatically given the full root context as the first parameter.

This means that
```
<!-- IF function.displayMenuItem, @index -->
```
is actually called like
```
<!-- IF function.displayMenuItem, @root, @index -->
```
This transformation for backwards compatibility does not occur when the new syntax is used, so to migrate you'll need to explicitly provide the root context:
```
{{{ if function.displayMenuItem, @root, @index }}}
xxxxx
{{{end}}}
```
Also, you may want to use the new helper syntax instead:
```
{{{ if displayMenuItem(@root, @index) }}}
xxxxx
{{{end}}}
```

**Comment by alfazaz** [comment]
Thanks !!!! I was far from thinking about all of these...

It works !
